[package]
name = "backend_project"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
sqlx = { version = "0.8.6", features = ["chrono", "mysql", "runtime-tokio"] }
tokio = { version = "1.45.1", features = ["full"] }
